Fix issue with nil properties not being set and passing hash with string keys issue
amco/dolly pull request #164
Opened 2021-04-14 17:15 UTC by ErickFabian

Fixes:
- Properties being set to nil would not be updated
- Passing a hash with string keys would cause a InvalidProperty error

2021-04-14 17:17 UTC, javierg requested changes
These are 2 issues, can you create 2 different PRs?

2021-04-14 17:22 UTC, ErickFabian commented
@javierg  Done, this is the other PR https://github.com/amco/dolly/pull/165

2021-05-10 18:21 UTC, javierg commented
@ErickFabian  can you write a test please.  I am not sure if this change will make any missing attribute on the model being removed.

2021-05-10 18:38 UTC, ErickFabian commented
@javierg I've added a spec for setting nil to a property on a doc

2021-05-11 13:58 UTC, javierg commented on test/property_manager_test.rb
> +    doc = TestDoc.new(name: 'name')
please add more properties, other than the one being updated

2021-05-11 19:27 UTC, javierg approved these changes
:shipit:

2021-05-11 19:27 UTC, merged